### ISSUE TITLE
SWA in vanilla Detectron2

### ISSUE THREAD

**Issue by markmno** [CPFLAME/centerX#49]
Could you please provide some guide how can I use SWA hook in Detectron2? Should I just add add additional config, or some code on CenternetTrainer is necessary?

Thanks!

**Comment by CPFLAME** [comment]
Swa has already provided in config,  you can add these code in your yaml
refer to `yamls/crowd_human/crowd_human_res18_swa.yaml`  
```
SOLVER:
  MAX_ITER: 70
  SWA:
    ENABLED: True
    ITER: 10
    PERIOD: 1
    LR_START: 0.002
    ETA_MIN_LR: 0.0001
    LR_SCHED: True
```
